version: '3.3'

services:
  app:
    image: ${APP_NAME}
    ipc: "host"
    privileged: true
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
      - DEBUG=y
      - TARGET_HTTP_SERVER=${HTTP_SERVER}
    volumes:
      - /usr/lib/libvdostream.so.1:/usr/lib/libvdostream.so.1
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:rw
      - /var/run/statuscache:/var/run/statuscache:rw
    devices:
      - /dev/datacache0:/dev/datacache0:rw

